locale:
- locale/**/*

workflow:
- .github/workflows/**/*
- .github/labeler.yml

documentation:
- .all-contributorsrc
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- CONTRIBUTORS.md
- LICENSE
- .github/FUNDING.yml
- .github/ISSUE_TEMPLATE/*

dependencies:
- package.json
- .github/renovate.json
- .github/workflows/dependency-review.yml

image:
- www/**/*

wontfix:
- payloads.json

code:
- functions/**/*
- helpers/*

automerge: # Translations are automatically merged if they have been approved inside Gitlocalize
- locale/**/*