name: Close-label
on:
- pull_request

jobs:
  close-label:
    runs-on: ubuntu-latest
    steps:
    - uses: larssieboy18/close-label@0.0.6
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
