# https://github.com/actions/first-interaction

name: First Interaction

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for creating an issue! We will take a look at your issue as soon as possible and keep you updated. If more details are needed, you will get a notification from Github by default.'
        pr-message: 'Thank you for your contribution! We will take a look at your PR as soon as possible and keep you updated. If more details are needed, you will get a notification from Github by default.'
