# https://github.com/dtinth/todo-actions
name: Create issues from todos

on: push

jobs:
  todos:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: todo-actions
      uses: dtinth/todo-actions@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TODO_ACTIONS_MONGO_URL: ${{ secrets.TODO_ACTIONS_MONGO_URL }}
